[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/single-property/*"
  to = "/single-property/index.html"
  status = 200

[[redirects]]
  from = "/properties/*"
  to = "/properties/index.html"
  status = 200
