[build]
  functions = "netlify/functions"
  publish = "."

[[redirects]]
  from = "/properties/*"
  to = "/single-property.html"
  status = 200

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
