[build]
  functions = "netlify/functions"
  publish = "."
[functions]
  node_bundler = "esbuild"
[[redirects]]
  from = "/single/property/*"
  to = "/single-property/:splat"
  status = 301
[[redirects]]
  from = "/property-detail/*"
  to = "/single-property/:splat"
  status = 301
